### PR TITLE
minutes of the 25th SG meeting

### PR DESCRIPTION
**Pull request by cportele**
Signed-off-by: Clemens Portele <portele@interactive-instruments.de>

### CODE REVIEW

**Comment by MarcoMinghini** [comment]
Dear Clemens,
thanks for the minutes. They are ok. Here just a couple of additional notes I took last time:

- about Pull Request #217, I think we decided to close it for the time being. We are managing the re-run function directly from the UI in the new INSPIRE UI.

- about the etf-result-checker, I took note of two actions for you to: add a comment about the issue with SoapUI tests in EIP #92; and open another EIP to start a discussion whether the SoapUI tests should be supported at all in the etf-result-checker.

I suggest to include these in the minutes before approval.

Thank you,
Marco

**Comment by cportele** [comment]
@MarcoMinghini - done, thanks. I have also updated EIP #92 and created draft EIP #99.

**Review by MarcoMinghini — APPROVED** [review]

**Review by jonherrmann — APPROVED** [review]

**Comment by jonherrmann** [comment]
Your GPG expired, Clemens @cportele (if it is you at all 🤨  )

image

**Comment by cportele** [comment]
Oops, thanks. I will fix that and copy the work from whoever wrote the minutes :wink: and create a new PR. Stay tuned...

**Comment by cportele** [comment]
Replaced by #101

**Pull request closed without merging**
